# Existing rule for all hostnames
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# New rule for a specific hostname
[[redirects]]
  from = "/*"
  to = "https://example.com/:splat"
  status = 301
  force = true
  conditions = {Host = ["isra-aid.org"]}
